### ISSUE TITLE
Powermail partial not found (case-sensitive file systems)

### ISSUE THREAD

**Issue by TehTux** [TehTux/jh_captcha#10]
Powermail partial not found on case-sensitive file systems...

`Tue, 11 Dec 2018 17:31:15 +0100 [ALERT] 
request="c6628e87e38c1" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": 
Oops, an error occurred! Code: 20181211173115adc18810 - 
{"exception":"TYPO3Fluid\\Fluid\\View\\Exception\\InvalidTemplateResourceException: The Fluid template files \"\/home\/typo3v8\/typo3conf\/ext\/jh_captcha\/Resources\/Private\/Powermail\/Partials\/Form\/Field\/JhCaptchaRecaptcha.html\", \"\/home\/typo3v8\/typo3conf\/ext\/jh_captcha\/Resources\/Private\/Powermail\/Partials\/Form\/Field\/JhCaptchaRecaptcha\", \"\/home\/typo3v8\/typo3conf\/ext\/powermail\/Resources\/Private\/Partials\/Form\/Field\/JhCaptchaRecaptcha.html\", \"\/home\/typo3v8\/typo3conf\/ext\/powermail\/Resources\/Private\/Partials\/Form\/Field\/JhCaptchaRecaptcha\" could not be loaded. in \/home\/typo3v8\/typo3_src-8.7.21\/vendor\/typo3fluid\/fluid\/src\/View\/TemplatePaths.php:730`

**Comment by Moongazer** [comment]
Confirmed. Just renaming the file to `/Resources/Private/Powermail/Partials/Form/Field/JhCaptchaRecaptcha.html` helps

**Comment by TehTux** [comment]
Fixed with 3.0.2
