### ISSUE TITLE
Oops, an error occurred! Code: 201911251334528cc9d495 - contact form

### ISSUE THREAD

**Issue by ds2k5** [TehTux/jh_captcha#16]
**Describe the bug**
did not work for me with: Typo3 9.5.11 and Bootstrap Package https://extensions.typo3.org/extension/bootstrap_package/

**To Reproduce**
1. Add Ext: jh_captcha
add Parmeters

Mastertemplate

https://www.bilder-upload.eu/bild-b3d3c9-1574685814.png.html

Template from ContactForm

https://www.bilder-upload.eu/bild-6aeed9-1574691079.png.html

2. create contact form

https://www.bilder-upload.eu/bild-a6f831-1574685684.png.html

3. open the form in Frontend

https://www.bilder-upload.eu/bild-5f0f94-1574685864.png.html

Oops, an error occurred! Code: 201911251334528cc9d495

If I remove reCaptcha from Contact Form, the Contact Form works fine.

**Expected behavior**

**Affected versions**
 - PHP: 7.3
 - TYPO3: 9.5.11
 - jh_captcha: 3.0.2
 - form: 9.5.11

**Additional context**

**Comment by TehTux** [comment]
Hello, thanks for your ticket. Your configuration is completely wrong. First you write that you are using form and then you use a configuration for formhandler. In TypoScript you write tx_jmrecaptcha, my extension is called tx_jhcaptcha. Additionally, "Oops, an error occurred!" doesn't say anything. You have to activate the error output to get a meaningful output.

**Comment by ds2k5** [comment]
Thank you.

My solution is now this:

on the Contact Site Template:

Constant:

`plugin.tx_jhcaptcha.settings.reCaptcha {
    v2 {
        siteKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        secretKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    }
    v3 {
        siteKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        secretKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    }
}

validators.1.config.fieldConf {
        jh_captcha_recaptcha.errorCheck {
            1 = required
            2 = \Haffner\JhCaptcha\Validation\ErrorCheck\ReCaptcha
        }
}
plugin.tx_jhcaptcha.settings.reCaptcha.version = 2
plugin.tx_jhcaptcha.settings.powermail.recaptchaId = 0`

Setup:

`
<div class="row">
    <div class="large-12 columns">
        ###jh_captcha_recaptcha###
        ###error_jh_captcha_recaptcha###
    </div>
</div>


###master_spamprotection-jh_captcha_recaptcha###
<label index="jh_captcha_recaptcha">reCAPTCHA</label>
<label index="error_jh_captcha_recaptcha_required">reCAPTCHA is a mandatory field.</label>
<label index="error_jh_captcha_recaptcha_recaptcha">reCAPTCHA validation error</label>  `
