### ISSUE TITLE
Old condition matching

### ISSUE THREAD

**Issue by ayacoo** [TehTux/jh_captcha#17]
**Describe the bug**
jh_captcha floods the error log with messages like this: 

`Tue, 03 Dec 2019 15:48:18 +0100 [WARNING] request="b113352c0c1c4" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = LIT:2 = 3"}`

**To Reproduce**
1. Install jh_captcha
2. Include typoscript template

**Affected versions**
 - PHP: 7.2
 - TYPO3: 9.5
 - jh_captcha: 3.0.2
 - form: Standard 9.5

**Additional context**
https://github.com/TehTux/jh_captcha/blob/develop/Configuration/TypoScript/setup.txt#L44

**Comment by TehTux** [comment]
Thanks for your message. I will fix it as soon as possible.

**Comment by a-r-m-i-n** [comment]
Do you still maintain this extension @TehTux ?

**Comment by bernd-reindl** [comment]
@TehTux you can solve this easy by replacing

[globalVar = LIT:2 = {$plugin.tx_jhcaptcha.settings.reCaptcha.version}]
    plugin.tx_powermail.settings.setup.spamshield.methods.{$plugin.tx_jhcaptcha.settings.powermail.recaptchaId} {
        configuration.secretkey = {$plugin.tx_jhcaptcha.settings.reCaptcha.v2.secretKey}
    }
[global]

with

[{$plugin.tx_jhcaptcha.settings.reCaptcha.version} == '2']
    plugin.tx_powermail.settings.setup.spamshield.methods.{$plugin.tx_jhcaptcha.settings.powermail.recaptchaId} {
        configuration.secretkey = {$plugin.tx_jhcaptcha.settings.reCaptcha.v2.secretKey}
    }
[END]

in setup.txt.

**Comment by bernd-reindl** [comment]
@TheTux this bug is still persistent.
