### ISSUE TITLE
Fluid template files loaded from wrong path

### ISSUE THREAD

**Issue by schuberttobias** [TehTux/jh_captcha#23]
**Describe the bug**
Typo3 loads jh_recaptcha fluid template files from the wrong path: 
* Actual location:  `(...)typo3conf/ext/jh_captcha/Resources/Private/Powermail/Partials/Form/Field/JhCaptchaRecaptcha.html`
* Location Typo3 uses `(...)/typo3conf/ext/powermail/Resources/Private/Partials/Form/Field/JhCaptchaRecaptcha.html`

Note that I used jh_recaptcha v3.0.3 and the issue is different from https://github.com/TehTux/jh_captcha/issues/10 .

Is this a configuration problem on my part or a bug?

**To Reproduce**
1. Install jh_captcha
2. Create a new form, with only 1 field of type jh_recaptcha
3. Save form
4. Visit form in frontend
5. Frontend displays: "Oops, an error occurred!"
6. Error logged to Typo3 Syslog:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1225709595: The Fluid template files "/var/www/<removed by schuberttobias>/httpdocs/typo3conf/ext/powermail/Resources/Private/Partials/Form/Field/JhCaptchaRecaptcha.html", "/var/www/<removed by schuberttobias>/httpdocs/typo3conf/ext/powermail/Resources/Private/Partials/Form/Field/JhCaptchaRecaptcha" could not be loaded. | TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException thrown in file /var/www/<removed by schuberttobias>/typo3_src-9.5.19/vendor/typo3fluid/fluid/src/View/TemplatePaths.php in line 730. Requested URL: https://dev.<removed by schuberttobias>/kontakt.html `

**Expected behavior**
Steps 1-4 identical as above
5. Frontend displays the form correctly

**Affected versions**
 - PHP: v7.2.24-0ubuntu0.18.04.6
 - TYPO3: 9.5.19
 - jh_captcha: 3.0.3
 - form/powermail/formhandler: powermail

**Comment by schuberttobias** [comment]
I have solved this in the Typo3 backend.
I added template "Google reCAPTCHA (v2/v3)" in Inlcudes -> "Include static (from extensions)" of my template.
Now the form renders correctly with the captcha and no errors are displayed or logged.
However, the [user manual](https://docs.typo3.org/p/haffner/jh_captcha/3.0/en-us/User/Index.html#) does not mention this step. Is it required?

**Comment by TehTux** [comment]
Yes, it is necessary. It is not mentioned separately, because it is so common with extensions in general.
