### ISSUE TITLE
TYPO3 11 compatibility 

### ISSUE THREAD

**Issue by rosty-matviiv** [TehTux/jh_captcha#28]
Would be awesome to have it compatible with TYPO3 11

**Comment by bernd-reindl** [comment]
Hello @TehTux ,

is there a plan to update the extension?

**Comment by Oktopuce** [comment]
Same question, are there any plan for TYPO3 V11 compatibility ?

**Comment by mansoorahmadhh** [comment]
any plan for TYPO3 V11 compatibility ?

**Comment by TehTux** [comment]
Release is today or tomorrow
