### ISSUE TITLE
Using this extension together with powermail and its confirmation page does not work.

### ISSUE THREAD

**Issue by weberdigital** [TehTux/jh_captcha#30]
**Describe the bug**
We are using this extension together with powermail and its confirmation page. The problem is, that the captcha is validated twice. Once after submitting the form and once after submitting the confirmation page.

There is an if condition at the start of `Haffner\JhCaptcha\Validation\Validator\Powermail::spamCheck`, to prevent multiple reCAPTCHA validations, but it's not working.

Also, loading the reCAPTCHA response from the form via `GeneralUtility::_GP("g-recaptcha-response")` does not work after submitting the confirmation page, because the parameter "g-recaptcha-response" does not exist in this case.

**To Reproduce**
1. Create a powermail form with a jh_recaptcha field.
2. Activate the confirmation page in the powermail plugin, which displays the form.
3. Fill out the form in the frontend and submit. This will take you to the confirmation page. With this form submit, the reCAPTCHA will be validated for the first time.
4. Submit the confirmation page. With this form submit, the reCAPTCHA will be validated for the second time, which will fail.

**Expected behavior**
The reCAPTCHA should only be validated after submitting the confirmation page.

**Affected versions**
 - PHP: 7.4
 - TYPO3: 10.4
 - jh_captcha: 4.0.0
 - powermail: 8.3.2

**Our suggestion for fixing this bug**
Change `Haffner\JhCaptcha\Validation\Validator\Powermail::spamCheck` to
```php
    public function spamCheck(): bool
    {
        # Skip captcha check on confirmation page
        if (
               GeneralUtility::_GPmerged('tx_powermail_pi1')['action'] === 'confirmation' // This has to be "confirmation" not "create".
                && $this->settings['main']['confirmation'] === '1' // We enable the confirmation page via TypoScript. Generally speaking, using $this->settings should be better than using $this->flexForm.
        ) {
            return false;
        }

        foreach ($this->mail->getAnswers() as $answer) {
            if ($answer->getField()->getType() == 'JhCaptchaRecaptcha') {
                /** @var ReCaptchaValidator $reCaptchaValidator */
                $reCaptchaValidator = GeneralUtility::makeInstance(ReCaptchaValidator::class);
                $result = $reCaptchaValidator->validate($answer->getValue()); // Don't read the value from GeneralUtility::_GP, because there are no _GP parameters after submitting the confirmation page.
                if (!empty($result->getErrors())) {
                    return true;
                }
            }
        }

        return false;
    }
```

In `Resources/Private/Powermail/Partials/Form/Field/JhCaptchaRecaptcha.html` change the view helper call to:
```
<jhcaptcha:reCaptcha
    uid="{f:if(condition: '{field.uid}', then: 'f{field.uid}', else: '')}"
    name="tx_powermail_pi1[field][{field.marker}]"
    type="powermail"
/>
```

In `Haffner\JhCaptcha\ViewHelpers\ReCaptchaViewHelper::initializeArguments` add
```php
$this->registerArgument('name', 'String', 'Name of the hidden input element', false);
```

In `Haffner\JhCaptcha\ViewHelpers\ReCaptchaViewHelper::renderV3` change the `if ($this->isPowermail())` to
```php
if ($this->isPowermail()) {
    $name = $this->arguments['name'] ?? 'g-recaptcha-response';
    $captchaResponseField = '<input type="hidden" id="' . $captchaResponseId . '" name="' . $name . '">';
}
```

Thank you very much in advance, for fixing the bug :)

**Comment by TehTux** [comment]
I can't reproduce this with a recent Powermail version. Please open a new ticket if necessary
