### ISSUE TITLE
Link to extension manual in the typo3 extension repository leads to outdated version

### ISSUE THREAD

**Issue by ghost** [TehTux/jh_captcha#6]

**Comment by TehTux** [comment]
Hi @fr33ztyl3,

i know, there are problems with the rendering in the TER. Which version do you need?

You can create a ticket here: https://github.com/t3docs/docker-render-documentation

**Comment by ghost** [comment]
I just found the URL myself, i needed https://docs.typo3.org/typo3cms/extensions/jh_captcha/3.0.0/User/Index.html

Thank you, keep the good work up!

Greez
Jan

**Comment by TehTux** [comment]
I contacted martin bless, https://docs.typo3.org/typo3cms/extensions/jh_captcha/ now links correctly to 3.0.0 and the missing 2.1.2 will be delivered immediately. I close the ticket.
