### ISSUE TITLE
Yaml config breaks on Case Sensitive 

### ISSUE THREAD

**Issue by foppelfb** [TehTux/jh_captcha#7]
Line 22 in jh_captcha/Configuration/Yaml/ReCaptcha/BaseSetup.yaml

              implementationClassName: 'Haffner\JhCaptcha\Validation\Validator\RecaptchaValidator'

while the Class is called ReCaptchaValidator

This breaks on Case Sensitive File systems
Reproducable in master and 3.0.1

**Comment by TehTux** [comment]
Fixed in 2.1.3 and 3.0.1
